Ankh-Morpork-webapp-MVC/Ankh-Morpork-webapp-MVC/Models/Assassin.cs
using Ankh_Morpork_game.Abstract;
using System.ComponentModel.DataAnnotations;

namespace Ankh_Morpork_webapp_MVC.Models
{
    public class Assassin : INPC
    {
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        public string Name { get; set; }
        public decimal MinReward { get; set; }
        public decimal MaxReward { get; set; }
        public bool IsOccupied { get; set; }
        public string ImageUrl { get; set; }

        public static void Kill(Player player)
        {
            player.IsAlive = false;
        }
    }
}

Ankh-Morpork-webapp-MVC/Ankh-Morpork-webapp-MVC/ViewModels/AssassinsIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ankh_Morpork_webapp_MVC.ViewModels
{
    public class AssassinsIndexViewModel
    {
        public string ImageUrl { get; set; }
        public string Message { get; set; }

    }
}

Ankh-Morpork-webapp-MVC/Ankh-Morpork-webapp-MVC/Controllers/AssassinsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ankh_Morpork_game.Guilds;
using Ankh_Morpork_webapp_MVC.Models;
using Ankh_Morpork_webapp_MVC.ViewModels;

namespace Ankh_Morpork_webapp_MVC.Controllers
{
    public class AssassinsController : Controller
    {
        private readonly AssassinsGuild _assassins = new AssassinsGuild();
        // GET: Assassins
        public ActionResult AssassinsIndex()
        {
            if (Player.GetPlayer().AmountOfMoney == 0 || !Player.GetPlayer().IsAlive)
                return RedirectToAction("GameOver", "Game");
            var assassin = _assassins.GeneratorOfNPC();
            var model = new MessageViewModel()
            {
                Money = Player.GetPlayer().MoneyMessage,
                Beers = Player.GetPlayer().AmountOfBeers,
                ImageUrl   = assassin.ImageUrl,
                Message = _assassins.Proposition
            };
            return View("AssassinsIndex",model);
        }

        public ActionResult Contract()
        {
            return View("Contract");
        }

        public ActionResult Skip()
        {
            return RedirectToAction("GameOver", "Game");
        }

        [HttpPost]
        public ActionResult SignContract(PlayerViewModel player)
        {
            if (!ModelState.IsValid)
            {
                return View("Contract", player);
            }
            bool isMadeContract = _assassins.CreateContract(Player.GetPlayer(), player.Payment);
            if (isMadeContract)
            {
                return RedirectToAction("NextStep", "Game");
            }
            return RedirectToAction("GameOver", "Game");
        }
    }
}

Ankh-Morpork-webapp-MVC/Ankh-Morpork-webapp-MVC/Views/Assassins/AssassinsIndex.cshtml
@model Ankh_Morpork_webapp_MVC.ViewModels.MessageViewModel
@{
    ViewBag.Title = "AssassinsIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-8 align-items-md-center">  
            <img src="~/Content/Images/Assassins/@(Model.ImageUrl)" class="img-thumbnail align-items-md-center"/>
        </div>
        <div class="col-4">
            @Html.Partial("_InfoView",new ViewDataDictionary(ViewData){{"Money", Model.Money}, {"Beers",Model.Beers}})
            <p class="bg-dark text-white fs-2">
                @Model.Message
            </p>
            @Html.ActionLink("Skip", "Skip", "Assassins", new {@class = "btn btn-secondary btn-lg"})
            @Html.ActionLink("Sign a contract!", "Contract", "Assassins", new {@class = "btn btn-secondary btn-lg"})
        </div>
    </div>
</div>

Ankh-Morpork-webapp-MVC/Ankh-Morpork-webapp-MVC/Views/Assassins/Contract.cshtml
@model Ankh_Morpork_webapp_MVC.ViewModels.PlayerViewModel
@{
    ViewBag.Title = "Contract";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 align="center">Contract</h2>
@using (Html.BeginForm("SignContract", "Assassins"))
{
    <div class="form-check" align="center">
        <div class="col-auto">
            <label class="col-form-label fs-4">Reward</label>
        </div>
        @Html.TextBoxFor(p => p.Payment, htmlAttributes:new {@class="field-validation-error"})<br/>
        @Html.ValidationMessageFor(p=>p.Payment)<br/>
        <button type="submit" class ="btn btn-primary">Submit</button>
    </div>
}