Ankh-Morpork-webapp-MVC/Ankh-Morpork-webapp-MVC/Models/Beggar.cs
using Ankh_Morpork_game.Abstract;
using Ankh_Morpork_game.Abstract.ChildInterfaces;
using System.ComponentModel.DataAnnotations;

namespace Ankh_Morpork_webapp_MVC.Models
{
    public class Beggar : AbstractFee,INPC
    {
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        public string Name { get; set; }
        public string ImageUrl { get; set; }
    }
}

Ankh-Morpork-webapp-MVC/Ankh-Morpork-webapp-MVC/Controllers/BeggarsController.cs
using Ankh_Morpork_game.Guilds;
using Ankh_Morpork_webapp_MVC.Models;
using System.Web.Mvc;

namespace Ankh_Morpork_webapp_MVC.Controllers
{
    public class BeggarsController : Controller
    {
        readonly BeggarsGuild _beggars = new BeggarsGuild();
        // GET: Beggars
        public ActionResult BeggarsIndex()
        {
            var beggar = _beggars.GeneratorOfNPC();
            if (Player.GetPlayer().AmountOfMoney == 0 || !Player.GetPlayer().IsAlive || (beggar.Fee==0 && Player.GetPlayer().AmountOfBeers==0))
                return RedirectToAction("GameOver", "Game");
            return View("BeggarsIndex",beggar);
        }
        public ActionResult Skip()
        {
            return RedirectToAction("GameOver", "Game");
        }
        public ActionResult Play(int id)
        {
            if (_beggars.GetNpc(id).Fee == 0)
                Player.GetPlayer().AmountOfBeers--;
            else
            {
                _beggars.GetNpc(id).GetFee(Player.GetPlayer());
            }
            return RedirectToAction("NextStep", "Game");
        }
    }
}

Ankh-Morpork-webapp-MVC/Ankh-Morpork-webapp-MVC/Views/Beggars/BeggarsIndex.cshtml
@using Ankh_Morpork_webapp_MVC.Data
@using Ankh_Morpork_webapp_MVC.Models
@model Ankh_Morpork_webapp_MVC.Models.Beggar
@{
    ViewBag.Title = "BeggarsIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-8 align-items-md-center">
            <img src="~/Content/Images/Beggars/@(Model.ImageUrl)" class="img-thumbnail align-items-md-center" />
        </div>
        <div class="col-4">
            @Html.Partial("_InfoView", new ViewDataDictionary(ViewData) { { "Money", MoneyFormatter.FormatMoney(Player.GetPlayer().AmountOfMoney) }, { "Beers", Player.GetPlayer().AmountOfBeers } })
            @if (Model.Fee != 0)
                {
                    <p class="bg-dark text-white fs-2">
                        Pay fee - @MoneyFormatter.FormatMoney(@Model.Fee) or I'll chase you to death
                    </p>
                }
            else
            {
                <p class="bg-dark text-white fs-2">Why lie? I need a beer!</p>
            }

            @Html.ActionLink("Skip", "Skip", "Beggars", new { @class = "btn btn-secondary btn-lg" })
            @Html.ActionLink("Play", "Play", "Beggars", new{id = Model.Id},new { @class = "btn btn-secondary btn-lg" })
        </div>
    </div>
</div>