Ankh-Morpork-webapp-MVC/Ankh-Morpork-webapp-MVC/Controllers/MendedDrumController.cs
using Ankh_Morpork_webapp_MVC.Models;
using System.Web.Mvc;

namespace Ankh_Morpork_webapp_MVC.Controllers
{
    public class MendedDrumController : Controller
    {
        // GET: Bar
        public ActionResult BarIndex()
        {
            return View("BarIndex");
        }

        [HttpPost]
        public ActionResult Buy(Bar bar)
        {
            Player.GetPlayer().Buy(bar.NumOfBeers, bar.Price);
            return RedirectToAction("NextStep", "Game");
        }
    }
}

Ankh-Morpork-webapp-MVC/Ankh-Morpork-webapp-MVC/Views/MendedDrum/BarIndex.cshtml
@model Ankh_Morpork_webapp_MVC.Models.Bar
@{
    ViewBag.Title = "BarIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .my-align {
        text-align: center
    }
</style>

<div>
    <div class="bg-light">
        <h2 class="my-align" >Welcome to Mended Drum</h2>
    </div>
    <div class="container">
        <div class="my-align bg-info">
            <p class ="fs-3">Here you can buy beer for Beggar</p>
        </div>
        <div class="row row-cols-4">
            <div class="col-6">
                <img src="~/Content/Images/City/mendedDrum.jpg" alt="Mended Drum" class="img-fluid"/>
            </div>
            <div class="col fw-bold">How many beers you wanna buy? <br/>(1 beer - 2AM$)</div>
            <div class="col">
            @using (Html.BeginForm("Buy", "MendedDrum"))
            {
                @Html.DropDownListFor(model => model.NumOfBeers, new SelectList(new List<int> {1, 2}))
                <button type="submit" class="btn btn-primary">Submit</button>
            }
            </div>
        </div>
    </div>
</div>