Ankh-Morpork-webapp-MVC/Ankh-Morpork-webapp-MVC/Controllers/ThievesController.cs
using Ankh_Morpork_game.Guilds;
using Ankh_Morpork_webapp_MVC.Models;
using System.Web.Mvc;

namespace Ankh_Morpork_webapp_MVC.Controllers
{
    public class ThievesController : Controller
    {
        private static readonly ThievesGuild Thieves = new ThievesGuild();
        // GET: Thieves
        public ActionResult ThievesIndex()
        {
            if (Player.GetPlayer().AmountOfMoney == 0 || !Player.GetPlayer().IsAlive)
                return RedirectToAction("GameOver", "Game");
            var thief = Thieves.GeneratorOfNPC();
            ThievesGuild.AcceptableNumberOfThefts--;
            return View("ThievesIndex", thief);
        }
        public ActionResult Skip()
        {
            return RedirectToAction("GameOver", "Game");
        }
        public ActionResult Play(int id)
        {
            Thieves.GetNpc(id).GetFee(Player.GetPlayer());
            return RedirectToAction("NextStep", "Game");
        }
    }
}

Ankh-Morpork-webapp-MVC/Ankh-Morpork-webapp-MVC/Views/Thieves/ThievesIndex.cshtml
@using Ankh_Morpork_webapp_MVC.Data
@using Ankh_Morpork_webapp_MVC.Models
@model Ankh_Morpork_webapp_MVC.Models.Thief
@{
    ViewBag.Title = "AssassinsIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-8 align-items-md-center">
            <img src="~/Content/Images/Thieves/@(Model.ImageUrl)" class="img-thumbnail align-items-md-center" />
        </div>
        <div class="col-4">
            @Html.Partial("_InfoView", new ViewDataDictionary(ViewData) { { "Money", MoneyFormatter.FormatMoney(Player.GetPlayer().AmountOfMoney) }, { "Beers", Player.GetPlayer().AmountOfBeers } })
            <p class="bg-dark text-white fs-2">
                Pay 10 bucks or you will be robbed
            </p>
            @Html.ActionLink("Skip", "Skip", "Thieves", new { @class = "btn btn-secondary btn-lg" })
            @Html.ActionLink("Play", "Play", "Thieves", new{id = Model.Id},new { @class = "btn btn-secondary btn-lg" })
        </div>
    </div>
</div>